# Generated by Django 5.1.4 on 2024-12-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade_date',
        ),
    ]
