# Generated by Django 5.1.4 on 2024-12-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0002_remove_grade_grade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='mobile_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
