# Generated by Django 5.1.4 on 2024-12-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0008_remove_projectteam_member_remove_projectteam_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectteam',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectteam',
            name='member',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectTeam',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
