# Generated by Django 5.1.4 on 2024-12-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0004_alter_grade_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=100)),
                ('text_field', models.TextField()),
                ('integer_field', models.IntegerField()),
                ('float_field', models.FloatField()),
                ('date_field', models.DateField()),
                ('boolean_field', models.BooleanField(default=False)),
                ('email_field', models.EmailField(max_length=254)),
                ('datetime_field', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
